using System;

using PocoDataSet.Extensions;
using PocoDataSet.IData;
using PocoDataSet.IObservableData;
using PocoDataSet.ObservableData;
using PocoDataSet.ObservableExtensions;

using Xunit;

namespace PocoDataSet.ObservableExtensionsTests.ObservableDataSetExtensions
{
    public partial class ObservableDataSetExtensionsTests
    {
        [Fact]
        public void MergeWithTest_PostSaveMode()
        {
            // Arrange
            // 1. Create a observable data set with a newly added row (client-side)
            IObservableDataSet observableDataSet = new ObservableDataSet();

            IObservableDataTable departmentObservableDataTable = observableDataSet.AddNewTable("Department");
            departmentObservableDataTable.AddColumn("Id", DataTypeNames.INT32); // identity in DB
            departmentObservableDataTable.AddColumn("Name", DataTypeNames.STRING);
            departmentObservableDataTable.AddColumn("RowVersion", DataTypeNames.BINARY); // rowversion/timestamp in DB

            IObservableDataRow departmentObservableDataRow = departmentObservableDataTable.AddNewRow();
            departmentObservableDataRow["Name"] = "Engineering";

            // At this moment the row is typically in Added state and has no identity / rowversion yet.
            // Get correlation data from row
            Guid clientKey = departmentObservableDataRow.GetDataFieldValue<Guid>(SpecialColumnNames.CLIENT_KEY);

            // 2. Build a server-returned data set after save
            // This data set contains the database-generated values for the same logical row.
            IDataSet postSaveDataSet = DataSetFactory.CreateDataSet();
            IDataTable postSaveDepartmentDataTable = postSaveDataSet.AddNewTable("Department");
            postSaveDepartmentDataTable.AddColumn("Id", DataTypeNames.INT32);
            postSaveDepartmentDataTable.AddColumn("Name", DataTypeNames.STRING);
            postSaveDepartmentDataTable.AddColumn("RowVersion", DataTypeNames.BINARY);

            IDataRow postSaveDepartmentDataRow = postSaveDepartmentDataTable.AddNewRow();
            postSaveDepartmentDataRow["Id"] = 10; // Imitate identity generated by DB
            postSaveDepartmentDataRow["Name"] = "Engineering";
            postSaveDepartmentDataRow["RowVersion"] = new byte[] { 1, 0, 0, 0, 0, 0, 0, 0 };

            // Imitate correlation between observable and saved rows
            postSaveDepartmentDataRow[SpecialColumnNames.CLIENT_KEY] = clientKey;

            // Act
            // 3. Merge server-returned values into the observable data set using PostSave mode
            IObservableMergeOptions observableMergeOptions = new ObservableMergeOptions();
            observableDataSet.DoPostSaveMerge(postSaveDataSet, observableMergeOptions);
            IObservableDataSetMergeResult mergeResult = observableMergeOptions.ObservableDataSetMergeResult;
// Assert
            // 4. Current row now has server-generated values (identity/rowversion) and is typically accepted as Unchanged by the merge handlers
            int id = departmentObservableDataTable.Rows[0].GetDataFieldValue<int>("Id"); // 10
            Assert.Equal(10, id);

            byte[]? rowVersion = departmentObservableDataTable.Rows[0].GetDataFieldValue<byte[]>("RowVersion");

            Assert.NotNull(rowVersion);
            Assert.Equal(new byte[] { 1, 0, 0, 0, 0, 0, 0, 0 }, rowVersion);
        }
    }
}
