using System;

using PocoDataSet.Extensions;
using PocoDataSet.IData;

using Xunit;

namespace PocoDataSet.ExtensionsTests
{
    public partial class DataSetExtensionsTests
    {
        [Fact]
        public void MergeWithTest_PostSaveMode()
        {
            // Arrange
            // 1. Create a current data set with a newly added row (client-side)
            IDataSet currentDataSet = DataSetFactory.CreateDataSet();

            IDataTable currentDepartment = currentDataSet.AddNewTable("Department");
            currentDepartment.AddColumn("Id", DataTypeNames.INT32); // identity in DB
            currentDepartment.AddColumn("Name", DataTypeNames.STRING);
            currentDepartment.AddColumn("RowVersion", DataTypeNames.BINARY); // rowversion/timestamp in DB

            IDataRow newRow = currentDepartment.AddNewRow();
            newRow["Name"] = "Engineering";

            // At this moment the row is typically in Added state and has no identity / rowversion yet.
            // Get correlation data from row
            Guid clientKey = newRow.GetDataFieldValue<Guid>(SpecialColumnNames.CLIENT_KEY);

            // 2. Build a server-returned data set after save
            // This data set contains the database-generated values for the same logical row.
            IDataSet postSaveDataSet = DataSetFactory.CreateDataSet();
            IDataTable postSaveDepartment = postSaveDataSet.AddNewTable("Department");
            postSaveDepartment.AddColumn("Id", DataTypeNames.INT32);
            postSaveDepartment.AddColumn("Name", DataTypeNames.STRING);
            postSaveDepartment.AddColumn("RowVersion", DataTypeNames.BINARY);

            IDataRow savedRow = postSaveDepartment.AddNewRow();
            savedRow["Id"] = 10; // identity generated by DB
            savedRow["Name"] = "Engineering";
            savedRow["RowVersion"] = new byte[] { 1, 0, 0, 0, 0, 0, 0, 0 };

            // Immitate correlation between new and saved rows
            savedRow[SpecialColumnNames.CLIENT_KEY] = clientKey;

            // Act
            // 3. Merge server-returned values into current data set using PostSave mode
            IDataSetMergeResult mergeResult = currentDataSet.MergeWith(postSaveDataSet, MergeMode.PostSave);

            // Assert
            // 4. Current row now has server-generated values (identity/rowversion) and is typically accepted as Unchanged by the merge handlers
            int id = currentDepartment.Rows[0].GetDataFieldValue<int>("Id"); // 10
            Assert.Equal(10, id);

            byte[]? rowVersion = currentDepartment.Rows[0].GetDataFieldValue<byte[]>("RowVersion");

            Assert.NotNull(rowVersion);
            Assert.Equal(new byte[] { 1, 0, 0, 0, 0, 0, 0, 0 }, rowVersion);
        }
    }
}
